name: CI

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  backend_test:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Run all backend tests
        run: ./mvnw --batch-mode test

  frontend_build:
    name: Frontend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run all Flutter tests
        run: flutter test

      - name: flutter build APK
        run: flutter build apk --release
